### ISSUE TITLE
hide "load more" button

### ISSUE THREAD

**Issue by n1ghtdev** [n1ghtdev/github-profile#2]
Hide "load more" button when there is no repositories to load.

**Comment by sarthakkundra** [comment]
Hi. I built the app to work on this. I have never used GraphQL before but I don't think this issue requires it's knowledge. Anyway on searching for users I'm getting an error saying API limit exceeded for 106.215.1.20. Maybe you can register the app for the API key so there can be more requests?

**Comment by n1ghtdev** [comment]
@sarthakkundra you're right you don't need any GraphQL knowledge to fix this one.

I'm not sure why this error is a thing for such small application, there is a chance that someone could hijack API key and use it on his own. Otherwise I cannot explain how a couple users can spend 5k request points / hour (it's about 1-10 points for request). 

Thanks.

**Comment by sarthakkundra** [comment]
@n1ghtdev do you mind generating a new key or if you allow I can use my API key to look into the issue and then can push it using the same. I'd appreciate it if you can tell me the file containing the API key if you want me to use mine so I can switch it faster.
Thanks.

**Comment by n1ghtdev** [comment]
@sarthakkundra you can create `.env` file in root project directory, which should contain next line:
```
REACT_APP_GITHUB_TOKEN=your_github_token
```
